spring.application.name=StarSystem
# Spring Boot so konfigurieren, dass Log4j2 verwendet wird
#logging.config=classpath:log4j2.xml

spring.devtools.restart.enabled=false
spring.main.allow-bean-definition-overriding=true
server.address=0.0.0.0

server.galaxyPath=/vs/v1/star

#logging.level.root=DEBUG

