spring.application.name=StarSystem
# Spring Boot so konfigurieren, dass Log4j2 verwendet wird
#logging.config=classpath:log4j2.xml

spring.devtools.restart.enabled=false
spring.main.allow-bean-definition-overriding=true
server.address= 0.0.0.0
#logging.level.root=DEBUG

#server.port=8006
